dlfkbnlknh('lgbnflgnn'
           'fgn'
           'fgnfnfn'
           'j'
           'ikj'
           'hgfd'
           'rtyu'
           'iuy'
           'tr'
           'sdcvbn')
rhpijrtipyyprojkwewpf